linters:
  disable-all: true
  enable:
  - asciicheck
  - bodyclose
  - contextcheck
  - cyclop
  - errcheck
  - exhaustive
  - copyloopvar
  - forcetypeassert
  - goimports
  - gosimple
  - govet
  - ineffassign
  - predeclared
  - staticcheck
  - usetesting
  - typecheck
  - unused
  - whitespace
