version: '3'

tasks:
  build-local:
    cmds:
      - go build -o terraform-provider-storyblok_{{ .VERSION }}
      - mkdir -p ~/.terraform.d/plugins/registry.terraform.io/labd/storyblok/{{ .VERSION }}/{{ .PLATFORM }}/
      - mv terraform-provider-storyblok_{{ .VERSION }} ~/.terraform.d/plugins/registry.terraform.io/labd/storyblok/{{ .VERSION }}/{{ .PLATFORM }}/terraform-provider-storyblok_v{{ .VERSION }}
      - cmd: codesign --deep --force -s - ~/.terraform.d/plugins/registry.terraform.io/labd/storyblok/{{ .VERSION }}/{{ .PLATFORM }}/terraform-provider-storyblok_v{{ .VERSION }}
        platforms: [ darwin ]
    vars:
      VERSION: 99.0.0
      PLATFORM:
        sh: echo "$(go env GOOS)_$(go env GOARCH)"

  format:
    cmds:
      - go fmt ./...

  test:
    cmds:
      - go test -v ./...

  docs:
    cmds:
      - go generate ./...

  coverage-html:
    cmds:
      - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
      - go tool cover -html=coverage.txt

  coverage:
    cmds:
      - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
      - go tool cover -func=coverage.txt

  testacc:
    cmds:
      - TF_ACC=1 STORYBLOK_URL=https://mapi.storyblok.com STORYBLOK_TOKEN=foobar go test ./...

